security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Domain\Access\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Domain\Access\Entity\User
                property: email

    role_hierarchy:
        ROLE_EXTERNAL: ROLE_USER
        ROLE_AGENT: ROLE_EXTERNAL
        ROLE_MANAGER: ROLE_AGENT
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_GOD: ROLE_ADMIN

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home
                enable_csrf: true
                csrf_token_id: logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/sso/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/sso/callback, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/admin/agent-request, roles: ROLE_MANAGER }
        - { path: ^/admin/demandes-cartes/pieces-jointes, roles: ROLE_MANAGER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/agents, roles: ROLE_AGENT }
        - { path: ^/espace-prive, roles: ROLE_USER }
        - { path: ^/extranet, roles: ROLE_USER }
        - { path: ^/api/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\Domain\Access\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
