twig:
    file_name_pattern: '*.twig'
    globals:
        app_cookie_consent_enabled: '%app.cookie_consent.enabled%'
        app_matomo_enabled: '%app.matomo.enabled%'
        app_matomo_site_id: '%app.matomo.site_id%'
        app_matomo_base_url: '%app.matomo.base_url%'
        app_god_mode: '@App\Application\Access\Service\GodModeService'

when@test:
    twig:
        strict_variables: true
