<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260423121500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema for Routes de Guadeloupe SIG portal with PostGIS bootstrap';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'postgis') THEN
        CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $$;");

        $this->addSql('CREATE TABLE app_role (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            label VARCHAR(120) NOT NULL,
            code VARCHAR(64) NOT NULL,
            description TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_role_code ON app_role (code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_app_role_uuid ON app_role (uuid)');

        $this->addSql('CREATE TABLE app_user (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            email VARCHAR(180) NOT NULL,
            password VARCHAR(255) NOT NULL,
            display_name VARCHAR(120) NOT NULL,
            is_active BOOLEAN NOT NULL,
            last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_uuid ON app_user (uuid)');

        $this->addSql('CREATE TABLE user_role (
            user_id INT NOT NULL,
            role_id INT NOT NULL,
            PRIMARY KEY(user_id, role_id)
        )');
        $this->addSql('CREATE INDEX idx_user_role_user ON user_role (user_id)');
        $this->addSql('CREATE INDEX idx_user_role_role ON user_role (role_id)');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES app_role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE audit_log (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            actor_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            action VARCHAR(120) NOT NULL,
            resource_type VARCHAR(120) NOT NULL,
            resource_identifier VARCHAR(120) DEFAULT NULL,
            ip_address VARCHAR(45) DEFAULT NULL,
            user_agent TEXT DEFAULT NULL,
            context JSON DEFAULT NULL,
            sensitive BOOLEAN NOT NULL,
            occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_audit_actor ON audit_log (actor_id)');
        $this->addSql('CREATE INDEX idx_audit_occurred_at ON audit_log (occurred_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_audit_log_uuid ON audit_log (uuid)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE taxonomy_term (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            parent_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            taxonomy VARCHAR(80) NOT NULL,
            slug VARCHAR(180) NOT NULL,
            label VARCHAR(180) NOT NULL,
            description TEXT DEFAULT NULL,
            active BOOLEAN NOT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_taxonomy_term_parent ON taxonomy_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_taxonomy_slug ON taxonomy_term (taxonomy, slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_taxonomy_term_uuid ON taxonomy_term (uuid)');
        $this->addSql('ALTER TABLE taxonomy_term ADD CONSTRAINT fk_taxonomy_parent FOREIGN KEY (parent_id) REFERENCES taxonomy_term (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE metadata_record (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            identifier VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            abstract_text TEXT DEFAULT NULL,
            keywords JSON DEFAULT NULL,
            raw_payload JSON DEFAULT NULL,
            last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_metadata_identifier ON metadata_record (identifier)');
        $this->addSql('CREATE UNIQUE INDEX uniq_metadata_record_uuid ON metadata_record (uuid)');

        $this->addSql('CREATE TABLE partner (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            name VARCHAR(180) NOT NULL,
            kind VARCHAR(32) NOT NULL,
            description TEXT DEFAULT NULL,
            website_url VARCHAR(512) DEFAULT NULL,
            logo_path VARCHAR(255) DEFAULT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_partner_slug ON partner (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_partner_uuid ON partner (uuid)');
        $this->addSql('CREATE INDEX idx_partner_created_by ON partner (created_by_id)');
        $this->addSql('CREATE INDEX idx_partner_updated_by ON partner (updated_by_id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT fk_partner_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT fk_partner_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE page (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            summary TEXT DEFAULT NULL,
            content TEXT NOT NULL,
            legal_type VARCHAR(64) DEFAULT NULL,
            system_page BOOLEAN NOT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_slug ON page (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_uuid ON page (uuid)');
        $this->addSql('CREATE INDEX idx_page_created_by ON page (created_by_id)');
        $this->addSql('CREATE INDEX idx_page_updated_by ON page (updated_by_id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_page_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT fk_page_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE news (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            summary TEXT DEFAULT NULL,
            body TEXT NOT NULL,
            cover_image_path VARCHAR(255) DEFAULT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_news_slug ON news (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_news_uuid ON news (uuid)');
        $this->addSql('CREATE INDEX idx_news_created_by ON news (created_by_id)');
        $this->addSql('CREATE INDEX idx_news_updated_by ON news (updated_by_id)');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT fk_news_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT fk_news_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE quick_link (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            label VARCHAR(160) NOT NULL,
            url VARCHAR(512) NOT NULL,
            position INT NOT NULL,
            external BOOLEAN NOT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_quick_link_uuid ON quick_link (uuid)');
        $this->addSql('CREATE INDEX idx_quick_link_created_by ON quick_link (created_by_id)');
        $this->addSql('CREATE INDEX idx_quick_link_updated_by ON quick_link (updated_by_id)');
        $this->addSql('ALTER TABLE quick_link ADD CONSTRAINT fk_quick_link_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quick_link ADD CONSTRAINT fk_quick_link_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE contact_message (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            full_name VARCHAR(150) NOT NULL,
            email VARCHAR(180) NOT NULL,
            subject VARCHAR(255) NOT NULL,
            message TEXT NOT NULL,
            status VARCHAR(32) NOT NULL,
            privacy_consent BOOLEAN NOT NULL,
            ip_address VARCHAR(45) DEFAULT NULL,
            submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_contact_message_uuid ON contact_message (uuid)');
        $this->addSql('CREATE INDEX idx_contact_message_status ON contact_message (status)');

        $this->addSql('CREATE TABLE map_service_endpoint (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            name VARCHAR(180) NOT NULL,
            service_type VARCHAR(32) NOT NULL,
            base_url VARCHAR(512) NOT NULL,
            auth_type VARCHAR(32) NOT NULL,
            credentials_ref VARCHAR(160) DEFAULT NULL,
            enabled BOOLEAN NOT NULL,
            timeout_ms INT NOT NULL,
            health_status VARCHAR(16) NOT NULL,
            last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            last_error TEXT DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_map_service_endpoint_uuid ON map_service_endpoint (uuid)');

        $this->addSql('CREATE TABLE static_map (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            metadata_record_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            summary TEXT DEFAULT NULL,
            description TEXT DEFAULT NULL,
            theme VARCHAR(120) DEFAULT NULL,
            keywords JSON DEFAULT NULL,
            document_date DATE DEFAULT NULL,
            thumbnail_path VARCHAR(255) DEFAULT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_static_map_slug ON static_map (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_static_map_uuid ON static_map (uuid)');
        $this->addSql('CREATE INDEX idx_static_map_status ON static_map (status)');
        $this->addSql('CREATE INDEX idx_static_map_created_by ON static_map (created_by_id)');
        $this->addSql('CREATE INDEX idx_static_map_updated_by ON static_map (updated_by_id)');
        $this->addSql('CREATE INDEX idx_static_map_metadata_record ON static_map (metadata_record_id)');
        $this->addSql('ALTER TABLE static_map ADD CONSTRAINT fk_static_map_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE static_map ADD CONSTRAINT fk_static_map_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE static_map ADD CONSTRAINT fk_static_map_metadata_record FOREIGN KEY (metadata_record_id) REFERENCES metadata_record (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE static_map_asset (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            static_map_id INT NOT NULL,
            uuid UUID NOT NULL,
            label VARCHAR(160) NOT NULL,
            asset_type VARCHAR(32) NOT NULL,
            file_path VARCHAR(255) NOT NULL,
            mime_type VARCHAR(120) DEFAULT NULL,
            file_size BIGINT DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_static_map_asset_uuid ON static_map_asset (uuid)');
        $this->addSql('CREATE INDEX idx_static_map_asset_map ON static_map_asset (static_map_id)');
        $this->addSql('ALTER TABLE static_map_asset ADD CONSTRAINT fk_static_map_asset_map FOREIGN KEY (static_map_id) REFERENCES static_map (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE dataset_resource (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            static_map_id INT NOT NULL,
            uuid UUID NOT NULL,
            label VARCHAR(160) NOT NULL,
            format VARCHAR(50) NOT NULL,
            external BOOLEAN NOT NULL,
            url VARCHAR(512) DEFAULT NULL,
            file_path VARCHAR(255) DEFAULT NULL,
            license VARCHAR(160) DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_dataset_resource_uuid ON dataset_resource (uuid)');
        $this->addSql('CREATE INDEX idx_dataset_resource_map ON dataset_resource (static_map_id)');
        $this->addSql('ALTER TABLE dataset_resource ADD CONSTRAINT fk_dataset_resource_map FOREIGN KEY (static_map_id) REFERENCES static_map (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE interactive_map (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            summary TEXT DEFAULT NULL,
            default_center_lat DOUBLE PRECISION NOT NULL,
            default_center_lng DOUBLE PRECISION NOT NULL,
            default_zoom INT NOT NULL,
            degraded_mode_message TEXT DEFAULT NULL,
            status VARCHAR(32) NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_interactive_map_slug ON interactive_map (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_interactive_map_uuid ON interactive_map (uuid)');
        $this->addSql('CREATE INDEX idx_interactive_map_created_by ON interactive_map (created_by_id)');
        $this->addSql('CREATE INDEX idx_interactive_map_updated_by ON interactive_map (updated_by_id)');
        $this->addSql('ALTER TABLE interactive_map ADD CONSTRAINT fk_interactive_map_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE interactive_map ADD CONSTRAINT fk_interactive_map_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE map_layer (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            interactive_map_id INT NOT NULL,
            endpoint_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            name VARCHAR(120) NOT NULL,
            label VARCHAR(180) NOT NULL,
            service_layer_name VARCHAR(180) DEFAULT NULL,
            layer_type VARCHAR(40) NOT NULL,
            render_order INT NOT NULL,
            visible_by_default BOOLEAN NOT NULL,
            style_config JSON DEFAULT NULL,
            filter_config JSON DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_map_layer_uuid ON map_layer (uuid)');
        $this->addSql('CREATE INDEX idx_map_layer_interactive_map ON map_layer (interactive_map_id)');
        $this->addSql('CREATE INDEX idx_map_layer_endpoint ON map_layer (endpoint_id)');
        $this->addSql('ALTER TABLE map_layer ADD CONSTRAINT fk_map_layer_interactive_map FOREIGN KEY (interactive_map_id) REFERENCES interactive_map (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE map_layer ADD CONSTRAINT fk_map_layer_endpoint FOREIGN KEY (endpoint_id) REFERENCES map_service_endpoint (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE agent_request_type (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            code VARCHAR(64) NOT NULL,
            label VARCHAR(160) NOT NULL,
            description TEXT DEFAULT NULL,
            requires_attachment BOOLEAN NOT NULL,
            active BOOLEAN NOT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_request_type_code ON agent_request_type (code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_request_type_uuid ON agent_request_type (uuid)');

        $this->addSql('CREATE TABLE agent_request (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            request_type_id INT NOT NULL,
            requester_id INT NOT NULL,
            assigned_to_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            request_number VARCHAR(40) NOT NULL,
            title VARCHAR(180) NOT NULL,
            description TEXT NOT NULL,
            status VARCHAR(32) NOT NULL,
            submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            payload JSON DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_request_number ON agent_request (request_number)');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_request_uuid ON agent_request (uuid)');
        $this->addSql('CREATE INDEX idx_agent_request_status ON agent_request (status)');
        $this->addSql('CREATE INDEX idx_agent_request_type ON agent_request (request_type_id)');
        $this->addSql('CREATE INDEX idx_agent_request_requester ON agent_request (requester_id)');
        $this->addSql('CREATE INDEX idx_agent_request_assigned_to ON agent_request (assigned_to_id)');
        $this->addSql('ALTER TABLE agent_request ADD CONSTRAINT fk_agent_request_type FOREIGN KEY (request_type_id) REFERENCES agent_request_type (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_request ADD CONSTRAINT fk_agent_request_requester FOREIGN KEY (requester_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_request ADD CONSTRAINT fk_agent_request_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE agent_request_attachment (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            agent_request_id INT NOT NULL,
            uuid UUID NOT NULL,
            original_name VARCHAR(255) NOT NULL,
            storage_path VARCHAR(255) NOT NULL,
            mime_type VARCHAR(120) NOT NULL,
            size_bytes BIGINT NOT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_agent_request_attachment_uuid ON agent_request_attachment (uuid)');
        $this->addSql('CREATE INDEX idx_agent_request_attachment_request ON agent_request_attachment (agent_request_id)');
        $this->addSql('ALTER TABLE agent_request_attachment ADD CONSTRAINT fk_agent_request_attachment_request FOREIGN KEY (agent_request_id) REFERENCES agent_request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE dashboard_metric_snapshot (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL,
            metric_key VARCHAR(120) NOT NULL,
            scope VARCHAR(80) DEFAULT NULL,
            recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            value_numeric NUMERIC(18, 4) DEFAULT NULL,
            value_integer BIGINT DEFAULT NULL,
            payload JSON DEFAULT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_dashboard_metric_snapshot_uuid ON dashboard_metric_snapshot (uuid)');
        $this->addSql('CREATE INDEX idx_dashboard_metric_key_recorded ON dashboard_metric_snapshot (metric_key, recorded_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE dashboard_metric_snapshot');
        $this->addSql('DROP TABLE agent_request_attachment');
        $this->addSql('DROP TABLE agent_request');
        $this->addSql('DROP TABLE agent_request_type');
        $this->addSql('DROP TABLE map_layer');
        $this->addSql('DROP TABLE interactive_map');
        $this->addSql('DROP TABLE dataset_resource');
        $this->addSql('DROP TABLE static_map_asset');
        $this->addSql('DROP TABLE static_map');
        $this->addSql('DROP TABLE map_service_endpoint');
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE quick_link');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE metadata_record');
        $this->addSql('DROP TABLE taxonomy_term');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE app_role');
    }
}
