<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add editable homepage hero and ordered homepage sections';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE homepage_content (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            name VARCHAR(120) NOT NULL,
            hero_title VARCHAR(255) NOT NULL,
            hero_baseline TEXT DEFAULT NULL,
            search_intro VARCHAR(180) DEFAULT NULL,
            search_placeholder VARCHAR(180) DEFAULT NULL,
            primary_cta_label VARCHAR(180) DEFAULT NULL,
            primary_cta_url VARCHAR(512) DEFAULT NULL,
            status VARCHAR(32) DEFAULT \'draft\' NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_homepage_content_uuid ON homepage_content (uuid)');
        $this->addSql('CREATE INDEX idx_homepage_content_created_by ON homepage_content (created_by_id)');
        $this->addSql('CREATE INDEX idx_homepage_content_updated_by ON homepage_content (updated_by_id)');
        $this->addSql('ALTER TABLE homepage_content ADD CONSTRAINT fk_homepage_content_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE homepage_content ADD CONSTRAINT fk_homepage_content_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE homepage_section (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            name VARCHAR(180) NOT NULL,
            type VARCHAR(48) NOT NULL,
            position INT DEFAULT 0 NOT NULL,
            title VARCHAR(255) NOT NULL,
            intro TEXT DEFAULT NULL,
            body TEXT DEFAULT NULL,
            image_path VARCHAR(255) DEFAULT NULL,
            cta_label VARCHAR(160) DEFAULT NULL,
            cta_url VARCHAR(512) DEFAULT NULL,
            layout VARCHAR(32) DEFAULT \'grid\' NOT NULL,
            background_style VARCHAR(32) DEFAULT \'light\' NOT NULL,
            item_limit INT DEFAULT 3 NOT NULL,
            items_config TEXT DEFAULT NULL,
            filters_config TEXT DEFAULT NULL,
            status VARCHAR(32) DEFAULT \'draft\' NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_homepage_section_uuid ON homepage_section (uuid)');
        $this->addSql('CREATE INDEX idx_homepage_section_created_by ON homepage_section (created_by_id)');
        $this->addSql('CREATE INDEX idx_homepage_section_updated_by ON homepage_section (updated_by_id)');
        $this->addSql('CREATE INDEX idx_homepage_section_status_position ON homepage_section (status, position)');
        $this->addSql('ALTER TABLE homepage_section ADD CONSTRAINT fk_homepage_section_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE homepage_section ADD CONSTRAINT fk_homepage_section_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE homepage_section DROP CONSTRAINT fk_homepage_section_created_by');
        $this->addSql('ALTER TABLE homepage_section DROP CONSTRAINT fk_homepage_section_updated_by');
        $this->addSql('ALTER TABLE homepage_content DROP CONSTRAINT fk_homepage_content_created_by');
        $this->addSql('ALTER TABLE homepage_content DROP CONSTRAINT fk_homepage_content_updated_by');
        $this->addSql('DROP TABLE homepage_section');
        $this->addSql('DROP TABLE homepage_content');
    }
}
