<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260506201122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add managed data categories and many-to-many relation with data sources';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE data_category (name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, icon_key VARCHAR(64) DEFAULT \'map\' NOT NULL, color_hex VARCHAR(7) DEFAULT \'#3CB4DF\' NOT NULL, featured_on_homepage BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT \'draft\' NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC92D01DD17F50A6 ON data_category (uuid)');
        $this->addSql('CREATE INDEX IDX_CC92D01DB03A8386 ON data_category (created_by_id)');
        $this->addSql('CREATE INDEX IDX_CC92D01D896DBBDE ON data_category (updated_by_id)');
        $this->addSql('CREATE INDEX idx_data_category_status_featured_position ON data_category (status, featured_on_homepage, position)');
        $this->addSql('CREATE UNIQUE INDEX uniq_data_category_slug ON data_category (slug)');
        $this->addSql('CREATE TABLE data_source_category (data_source_id INT NOT NULL, data_category_id INT NOT NULL, PRIMARY KEY (data_source_id, data_category_id))');
        $this->addSql('CREATE INDEX IDX_30DDC6041A935C57 ON data_source_category (data_source_id)');
        $this->addSql('CREATE INDEX IDX_30DDC604ED86C2A8 ON data_source_category (data_category_id)');
        $this->addSql('ALTER TABLE data_category ADD CONSTRAINT FK_CC92D01DB03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE data_category ADD CONSTRAINT FK_CC92D01D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE data_source_category ADD CONSTRAINT FK_30DDC6041A935C57 FOREIGN KEY (data_source_id) REFERENCES data_source (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE data_source_category ADD CONSTRAINT FK_30DDC604ED86C2A8 FOREIGN KEY (data_category_id) REFERENCES data_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("INSERT INTO data_category (name, slug, description, icon_key, color_hex, featured_on_homepage, position, uuid, created_at, updated_at, status, published_at) VALUES ('Données ouvertes', 'donnees-ouvertes', 'Jeux de données téléchargeables et réutilisables.', 'database', '#3CB4DF', true, 10, '44aa6f5f-c7f5-4ca4-a50d-d77f7db8fda5', NOW(), NOW(), 'published', NOW())");
        $this->addSql("INSERT INTO data_category (name, slug, description, icon_key, color_hex, featured_on_homepage, position, uuid, created_at, updated_at, status, published_at) VALUES ('Cartes statiques', 'cartes-statiques', 'Cartothèque de cartes prêtes à consulter.', 'map', '#FF4D0A', true, 20, '72d8afb3-61a8-4aad-bf84-50a39b7738a6', NOW(), NOW(), 'published', NOW())");
        $this->addSql("INSERT INTO data_category (name, slug, description, icon_key, color_hex, featured_on_homepage, position, uuid, created_at, updated_at, status, published_at) VALUES ('Cartes interactives', 'cartes-interactives', 'Visualisations dynamiques et couches superposables.', 'layers', '#2FA7D9', true, 30, '3df29373-d01d-4b56-b2f4-56f8f75a4d5e', NOW(), NOW(), 'published', NOW())");
        $this->addSql("INSERT INTO data_category (name, slug, description, icon_key, color_hex, featured_on_homepage, position, uuid, created_at, updated_at, status, published_at) VALUES ('Services SIG', 'services-sig', 'Services WMS/WFS et endpoints de diffusion.', 'sig', '#7AA63A', true, 40, '34f73029-7f14-4cb2-bf09-2a7691fc531b', NOW(), NOW(), 'published', NOW())");
        $this->addSql("INSERT INTO data_source_category (data_source_id, data_category_id) SELECT s.id, c.id FROM data_source s JOIN data_category c ON c.slug = 'donnees-ouvertes' WHERE s.source_type = 'data_file'");
        $this->addSql("INSERT INTO data_source_category (data_source_id, data_category_id) SELECT s.id, c.id FROM data_source s JOIN data_category c ON c.slug = 'cartes-statiques' WHERE s.source_type = 'static_map'");
        $this->addSql("INSERT INTO data_source_category (data_source_id, data_category_id) SELECT s.id, c.id FROM data_source s JOIN data_category c ON c.slug = 'cartes-interactives' WHERE s.source_type = 'cartography_link'");
        $this->addSql("INSERT INTO data_source_category (data_source_id, data_category_id) SELECT s.id, c.id FROM data_source s JOIN data_category c ON c.slug = 'services-sig' WHERE s.source_type IN ('wms', 'wfs', 'cartography_link')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE data_category DROP CONSTRAINT FK_CC92D01DB03A8386');
        $this->addSql('ALTER TABLE data_category DROP CONSTRAINT FK_CC92D01D896DBBDE');
        $this->addSql('ALTER TABLE data_source_category DROP CONSTRAINT FK_30DDC6041A935C57');
        $this->addSql('ALTER TABLE data_source_category DROP CONSTRAINT FK_30DDC604ED86C2A8');
        $this->addSql('DROP TABLE data_category');
        $this->addSql('DROP TABLE data_source_category');
    }
}
