<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506120222 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add external user management (profile/SSO), resource visibility scopes, favorites and external resource requests';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE app_user ADD user_type VARCHAR(40) DEFAULT \'external_professional\' NOT NULL');
        $this->addSql('ALTER TABLE app_user ADD first_name VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD last_name VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD organization_name VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD website_url VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD auth_provider VARCHAR(16) DEFAULT \'local\' NOT NULL');
        $this->addSql('ALTER TABLE app_user ADD sso_subject VARCHAR(190) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_sso_subject ON app_user (sso_subject)');

        $this->addSql('CREATE TABLE external_resource_request (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            requester_id INT NOT NULL,
            uuid UUID NOT NULL,
            subject VARCHAR(180) NOT NULL,
            message TEXT NOT NULL,
            status VARCHAR(32) DEFAULT \'submitted\' NOT NULL,
            submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            metadata JSON DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_external_resource_request_uuid ON external_resource_request (uuid)');
        $this->addSql('CREATE INDEX idx_external_request_user ON external_resource_request (requester_id)');
        $this->addSql('CREATE INDEX idx_external_request_status ON external_resource_request (status)');
        $this->addSql('ALTER TABLE external_resource_request ADD CONSTRAINT fk_external_request_user FOREIGN KEY (requester_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE user_favorite (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            uuid UUID NOT NULL,
            resource_kind VARCHAR(32) NOT NULL,
            resource_slug VARCHAR(180) NOT NULL,
            resource_title VARCHAR(255) NOT NULL,
            resource_url VARCHAR(512) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_favorite_uuid ON user_favorite (uuid)');
        $this->addSql('CREATE INDEX idx_user_favorite_user ON user_favorite (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_favorite ON user_favorite (user_id, resource_kind, resource_slug)');
        $this->addSql('ALTER TABLE user_favorite ADD CONSTRAINT fk_user_favorite_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE data_source ADD visibility_scope VARCHAR(16) DEFAULT \'public\' NOT NULL');
        $this->addSql('ALTER TABLE dataset_resource ADD visibility_scope VARCHAR(16) DEFAULT \'public\' NOT NULL');
        $this->addSql('ALTER TABLE interactive_map ADD visibility_scope VARCHAR(16) DEFAULT \'public\' NOT NULL');
        $this->addSql('ALTER TABLE static_map ADD visibility_scope VARCHAR(16) DEFAULT \'public\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE external_resource_request DROP CONSTRAINT fk_external_request_user');
        $this->addSql('ALTER TABLE user_favorite DROP CONSTRAINT fk_user_favorite_user');
        $this->addSql('DROP TABLE external_resource_request');
        $this->addSql('DROP TABLE user_favorite');

        $this->addSql('DROP INDEX uniq_user_sso_subject');
        $this->addSql('ALTER TABLE app_user DROP user_type');
        $this->addSql('ALTER TABLE app_user DROP first_name');
        $this->addSql('ALTER TABLE app_user DROP last_name');
        $this->addSql('ALTER TABLE app_user DROP organization_name');
        $this->addSql('ALTER TABLE app_user DROP website_url');
        $this->addSql('ALTER TABLE app_user DROP auth_provider');
        $this->addSql('ALTER TABLE app_user DROP sso_subject');

        $this->addSql('ALTER TABLE data_source DROP visibility_scope');
        $this->addSql('ALTER TABLE dataset_resource DROP visibility_scope');
        $this->addSql('ALTER TABLE interactive_map DROP visibility_scope');
        $this->addSql('ALTER TABLE static_map DROP visibility_scope');
    }
}
