<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260505100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add unified data sources for catalog entries';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE data_source (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            linked_static_map_id INT DEFAULT NULL,
            linked_interactive_map_id INT DEFAULT NULL,
            service_endpoint_id INT DEFAULT NULL,
            created_by_id INT DEFAULT NULL,
            updated_by_id INT DEFAULT NULL,
            uuid UUID NOT NULL,
            slug VARCHAR(180) NOT NULL,
            title VARCHAR(255) NOT NULL,
            source_type VARCHAR(40) DEFAULT \'data_file\' NOT NULL,
            summary TEXT DEFAULT NULL,
            description TEXT DEFAULT NULL,
            theme VARCHAR(120) DEFAULT NULL,
            keywords JSON DEFAULT NULL,
            source_url VARCHAR(512) DEFAULT NULL,
            file_path VARCHAR(255) DEFAULT NULL,
            format VARCHAR(50) DEFAULT NULL,
            license VARCHAR(160) DEFAULT NULL,
            thumbnail_path VARCHAR(255) DEFAULT NULL,
            status VARCHAR(32) DEFAULT \'draft\' NOT NULL,
            published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_data_source_slug ON data_source (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_data_source_uuid ON data_source (uuid)');
        $this->addSql('CREATE INDEX idx_data_source_type_status ON data_source (source_type, status)');
        $this->addSql('CREATE INDEX idx_data_source_theme ON data_source (theme)');
        $this->addSql('CREATE INDEX idx_data_source_linked_static_map ON data_source (linked_static_map_id)');
        $this->addSql('CREATE INDEX idx_data_source_linked_interactive_map ON data_source (linked_interactive_map_id)');
        $this->addSql('CREATE INDEX idx_data_source_service_endpoint ON data_source (service_endpoint_id)');
        $this->addSql('CREATE INDEX idx_data_source_created_by ON data_source (created_by_id)');
        $this->addSql('CREATE INDEX idx_data_source_updated_by ON data_source (updated_by_id)');
        $this->addSql('ALTER TABLE data_source ADD CONSTRAINT fk_data_source_linked_static_map FOREIGN KEY (linked_static_map_id) REFERENCES static_map (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_source ADD CONSTRAINT fk_data_source_linked_interactive_map FOREIGN KEY (linked_interactive_map_id) REFERENCES interactive_map (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_source ADD CONSTRAINT fk_data_source_service_endpoint FOREIGN KEY (service_endpoint_id) REFERENCES map_service_endpoint (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_source ADD CONSTRAINT fk_data_source_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_source ADD CONSTRAINT fk_data_source_updated_by FOREIGN KEY (updated_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE data_source DROP CONSTRAINT fk_data_source_linked_static_map');
        $this->addSql('ALTER TABLE data_source DROP CONSTRAINT fk_data_source_linked_interactive_map');
        $this->addSql('ALTER TABLE data_source DROP CONSTRAINT fk_data_source_service_endpoint');
        $this->addSql('ALTER TABLE data_source DROP CONSTRAINT fk_data_source_created_by');
        $this->addSql('ALTER TABLE data_source DROP CONSTRAINT fk_data_source_updated_by');
        $this->addSql('DROP TABLE data_source');
    }
}
